default_language_version:
  python: python3
exclude: '\.(tsv|fasta|gb)$|^shared/vendored/'
repos:
  - repo: https://github.com/pre-commit/sync-pre-commit-deps
    rev: v0.0.1
    hooks:
      - id: sync-pre-commit-deps
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
  - repo: https://github.com/rhysd/actionlint
    rev: v1.6.27
    hooks:
      - id: actionlint
        entry: env SHELLCHECK_OPTS='--exclude=SC2027' actionlint
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-ast # Check Python files for valid syntax
      - id: check-case-conflict # Check for files with names that would conflict on case-insensitive filesystems
      - id: check-docstring-first # Check Python files have docstrings before imports
      - id: check-json
      - id: check-executables-have-shebangs
      - id: check-merge-conflict # Check for merge conflict markers 
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: destroyed-symlinks # Check for symlinks pointing to non-existent files
      - id: detect-private-key # Check for private keys accidentally committed
      - id: fix-byte-order-marker # Remove byte order marker from files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.6
    hooks:
      # Run the python linter `ruff` to enforce style and catch issues
      # See the `pyproject.toml` file for configuration
      - id: ruff
