#!/usr/bin/env python3
import json
from sys import argv, exit, stderr


# Start with configuration shared between datasets
config = {
  "maintainers": [
    {"name": "the Nextstrain team", "url": "https://nextstrain.org/team"}
  ],
  "build_url": "https://github.com/nextstrain/ebola",
  "colorings": [
    {
      "key": "gt",
      "title": "Genotype",
      "type": "categorical"
    },
    {
      "key": "num_date",
      "title": "Date",
      "type": "continuous"
    },
    {
      "key": "author",
      "title": "Author",
      "type":"categorical"
    },
    {
      "key": "country",
      "title": "Country",
      "type": "categorical"
    },
    {
      "key": "division",
      "title": "Division",
      "type": "categorical"
    }
  ],
  "geo_resolutions": [
    "country",
    "division"
  ],
  "metadata_columns": [
    "strain"
  ],
  "display_defaults": {
    "color_by": "country",
    "geo_resolution": "country",
    "tip_label": "strain"
  },
  "filters": [
    "country",
    "division",
    "author"
  ]
}


def main(dataset):
    if dataset == "west-africa-2014":
        config["title"] = "Genomic epidemiology of the 2013-2016 West African Ebola epidemic"
    else:
        print(f"No configuration for dataset {dataset!r}.", file=stderr)
        return 1

    print(json.dumps(config, indent=2))


if __name__ == "__main__":
    if len(argv) != 2:
        print("Usage: {} <dataset>".format(argv[0]), file=stderr)
        exit(1)
    exit(main(argv[1]))
