from snakemake.utils import min_version
import os 

# Minimum Snakemake version needed for the storage plugins used in remote_files.smk
min_version("8.0.0")

# Set up config structure first
include: "../shared/vendored/snakemake/config.smk"
include: "rules/config.smk"

configfile: os.path.join(workflow.basedir, 'defaults', 'config.yaml')
if os.path.exists("config.yaml"):
    configfile: "config.yaml"
validate_config()
write_subsample_configs()

# certain commands (but not all) use SEARCH_PATHS
SEARCH_PATHS = [workflow.basedir, os.getcwd()]

wildcard_constraints:
    species=r"[^/_]+",
    build=r"[^/_]+",

include: "../shared/vendored/snakemake/remote_files.smk"
include: "rules/multiple_inputs.smk"
include: "rules/nextclade.smk"
include: "rules/subsample.smk"
include: "rules/construct_phylogeny.smk"


rule all:
    input:
        # TODO - update as capabilities added...
        expand("results/{build_pair}/tree.nwk", build_pair=config['builds']),
