# This configuration file should contain all required configuration parameters
# for the ingest workflow to run with additional Nextstrain automation rules.

# Custom rules to run as part of the Nextstrain automated workflow
# The paths should be relative to the ingest directory.
custom_rules:
  - build-configs/nextstrain-automation/upload.smk

# Nextstrain CloudFront domain to ensure that we invalidate CloudFront after the S3 uploads
# This is required as long as we are using the AWS CLI for uploads
cloudfront_domain: "data.nextstrain.org"

# Nextstrain AWS S3 Bucket with pathogen prefix
s3_dst: "s3://nextstrain-data/files/workflows/ebola"

# Mapping of files to upload
files_to_upload:
  ebov/metadata_open.tsv.zst: results/ebov/metadata_open.tsv
  ebov/metadata_restricted.tsv.zst: results/ebov/metadata_restricted.tsv
  ebov/sequences_open.fasta.zst: results/ebov/sequences_open.fasta
  ebov/sequences_restricted.fasta.zst: results/ebov/sequences_restricted.fasta

  bdbv/metadata_open.tsv.zst: results/bdbv/metadata_open.tsv
  bdbv/metadata_restricted.tsv.zst: results/bdbv/metadata_restricted.tsv
  bdbv/sequences_open.fasta.zst: results/bdbv/sequences_open.fasta
  bdbv/sequences_restricted.fasta.zst: results/bdbv/sequences_restricted.fasta

  sudv/metadata_open.tsv.zst: results/sudv/metadata_open.tsv
  sudv/metadata_restricted.tsv.zst: results/sudv/metadata_restricted.tsv
  sudv/sequences_open.fasta.zst: results/sudv/sequences_open.fasta
  sudv/sequences_restricted.fasta.zst: results/sudv/sequences_restricted.fasta
  