
# TODO XXX - move inputs to nextstrain-data before PR merge
inputs:
  - name: ppx_open
    species: ebov
    metadata: "s3://nextstrain-staging/files/workflows/ebola/ebov/metadata_open.tsv.zst"
    sequences: "s3://nextstrain-staging/files/workflows/ebola/ebov/sequences_open.fasta.zst"
  - name: ppx_open
    species: bdbv
    metadata: "s3://nextstrain-staging/files/workflows/ebola/bdbv/metadata_open.tsv.zst"
    sequences: "s3://nextstrain-staging/files/workflows/ebola/bdbv/sequences_open.fasta.zst"
  - name: ppx_open
    species: sudv
    metadata: "s3://nextstrain-staging/files/workflows/ebola/sudv/metadata_open.tsv.zst"
    sequences: "s3://nextstrain-staging/files/workflows/ebola/sudv/sequences_open.fasta.zst"

strain_id_field: accession # TODO XXX - this isn't ergonomic for injecting private data

builds:
   - bdbv/all-outbreaks
   - bdbv/2026 # TODO XXX - is this the best name?
   - sudv/all-outbreaks
   - ebov/all-outbreaks
   - ebov/west-africa-2014

nextclade:
  ebov:
    dataset-name: nextstrain/orthoebolavirus/ebov
    columns:
      - [clade, outbreak]
      - [qc.overallStatus, nextclade_qc]
      - [coverage, genome_coverage]
  bdbv:
    dataset-name: nextstrain/orthoebolavirus/bdbv 
    columns:
      - [outbreak, outbreak]
      - [qc.overallStatus, nextclade_qc]
      - [coverage, genome_coverage]
  sudv:
    dataset-name: nextstrain/orthoebolavirus/sudv
    columns:
      - [qc.overallStatus, nextclade_qc]
      - [coverage, genome_coverage]

# See <https://docs.nextstrain.org/projects/augur/en/latest/usage/cli/subsample.html> for subsample
# config schema docs
subsample:
  ebov/all-outbreaks:
    samples:
      everything:
         min_length: 18000
         include: defaults/include_ebov_all-outbreaks.txt
         group_by: [outbreak, country, year]
         sequences_per_group: 25
         exclude_where: is_lab_host=true
  ebov/west-africa-2014:
    samples:
      outbreak:
        min_length: 18000
        include: defaults/include_ebov_west-africa-2014.txt
        group_by: [division, year, month]
        sequences_per_group: 30
        exclude_where: is_lab_host=true
        query: '(outbreak=="Ebov-2013" | outbreak=="Ebov-2013/r2021")'
  bdbv/all-outbreaks:
    samples:
      everything:
         min_length: 5000
  bdbv/2026:
    samples:
      outbreak:
        min_length: 5000
        exclude_where: outbreak!=Bdbv-2026
  sudv/all-outbreaks:
    samples:
      everything:
        min_length: 5000
        exclude: defaults/exclude_sudv.txt

# per-build masking (optional)
mask:
  sudv/all-outbreaks: &generic-masking
    beginning: 50
    end: 50
  bdbv/all-outbreaks:
    <<: *generic-masking
  bdbv/2026:
    <<: *generic-masking

# per-build tree re-rooting (before refine). Optional.
reroot_tree:
  ebov/all-outbreaks:
    # See <https://virological.org/t/on-the-rooting-of-the-ebola-virus-phylogeny-and-its-consequences-for-understanding-the-diversity-in-the-reservoir/1005> for rooting approach
    strains: ['PP_000LE61', 'PP_000NUJS']

# per-build arguments to `augur refine`
refine:
  ebov/all-outbreaks: >-
    --keep-root
  ebov/west-africa-2014: >-
    --timetree
    --date-inference marginal
    --coalescent skyline
    --date-confidence
  bdbv/all-outbreaks: >-
    --root mid_point
    --keep-polytomies
  sudv/all-outbreaks: >-
    --root mid_point
    --keep-polytomies
  # bdbv/2026 is a WIP - starting with the same args as west-africa
  bdbv/2026: >-
    --timetree
    --date-inference marginal
    --coalescent skyline
    --date-confidence