# This configuration file should contain all required configuration parameters
# for the phylogenetic workflow to run to completion.
#
# Define optional config parameters with their default values here so that users
# do not have to dig through the workflows to figure out the default values

id_column: "accession"

builds:
  - all-outbreaks
  # - west-africa-2014

build_params:
  all-outbreaks:
    ancestral:
      inference: joint

    files:
      reference: defaults/all-outbreaks/NC_002549.1.gb
      colors: defaults/colors.tsv
      lat_longs: defaults/lat_longs.tsv
      auspice_config: defaults/all-outbreaks/auspice_config.json
      description: defaults/all-outbreaks/description.md
      clades: defaults/all-outbreaks/clades.tsv

    filter:
      min_length: 18000
      exclude_where: is_lab_host=true
      exclude: defaults/exclude.txt
      include: defaults/all-outbreaks/include.txt
      subsample_max_sequences: 400
      group_by:
        - country
        - year

    refine:
      timetree: true
      coalescent: skyline
      date_inference: marginal

    traits:
      columns:
        - country
        - division

    export:
      warning: >-
        Work in progress.

  west-africa-2014:
    ancestral:
      inference: joint

    files:
      reference: defaults/west-africa-2014/ebola_outgroup.gb
      colors: defaults/colors.tsv
      lat_longs: defaults/lat_longs.tsv
      auspice_config: defaults/west-africa-2014/auspice_config.json
      description: defaults/west-africa-2014/description.md

    filter:
      min_length: 18000
      exclude_where: is_lab_host=true
      exclude: defaults/exclude.txt
      include: defaults/west-africa-2014/include.txt
      subsample_max_sequences: 1500
      min_date: 2012
      max_date: 2017
      group_by:
        - division
        - year
        - month

    refine:
      timetree: true
      coalescent: skyline
      date_inference: marginal

    traits:
      columns:
        - country
        - division

    export:
      warning: defaults/west-africa-2014/description.md
