# This configuration file should contain all required configuration parameters
# for the phylogenetic workflow to run to completion.
#
# Define optional config parameters with their default values here so that users
# do not have to dig through the workflows to figure out the default values

id_column: "accession"

ancestral:
  inference: joint

files:
  reference: defaults/ebola_outgroup.gb
  colors: defaults/colors.tsv
  lat_longs: defaults/lat_longs.tsv
  auspice_config: defaults/auspice_config.json
  description: defaults/description.md

filter:
  exclude: defaults/exclude.txt
  include: defaults/include.txt
  subsample_max_sequences: 1500
  min_date: 2012
  max_date: 2017
  group_by:
    - division
    - year
    - month

refine:
  coalescent: skyline
  date_inference: marginal

traits:
  columns:
    - country
    - division
