# This configuration file should contain all required configuration parameters
# for the phylogenetic workflow to run to completion.
#
# Define optional config parameters with their default values here so that users
# do not have to dig through the workflows to figure out the default values

id_column: "accession"

inputs:
  - name: local_ingest
    metadata: ../ingest/results/metadata.tsv
    sequences: ../ingest/results/sequences.fasta

builds:
  - drc-2025
  # - west-africa-2014

build_params:
  drc-2025:
    ancestral:
      inference: joint

    files:
      reference: drc-2025/NC_002549.1.gb  # FIXME: use another reference?
      lat_longs: ../defaults/lat_longs.tsv
      auspice_config: drc-2025/auspice_config.json
      description: drc-2025/description.md

    filter:
      min_length: 18000
      exclude: ../defaults/exclude.txt
      include: drc-2025/include.txt
      min_date: "2025-08-01"
      exclude_ambiguous_dates_by: month

    refine:
      timetree: false
      coalescent: skyline
      date_inference: marginal

    traits:
      columns:
        - country
        - division

    export:
      warning: >-
        Work in progress.

  west-africa-2014:
    ancestral:
      inference: joint

    files:
      reference: west-africa-2014/ebola_outgroup.gb
      lat_longs: ../defaults/lat_longs.tsv
      auspice_config: west-africa-2014/auspice_config.json
      description: west-africa-2014/description.md

    filter:
      min_length: 18000
      exclude_where: is_lab_host=true
      exclude: ../defaults/exclude.txt
      include: west-africa-2014/include.txt
      subsample_max_sequences: 30
      min_date: 2012
      max_date: 2017
      group_by:
        - division
        - year
        - month

    refine:
      timetree: true
      coalescent: skyline
      date_inference: marginal

    traits:
      columns:
        - country
        - division

    export:
      warning: west-africa-2014/description.md
