# This configuration file should contain all required configuration parameters
# for the phylogenetic workflow to run to completion.
#
# Define optional config parameters with their default values here so that users
# do not have to dig through the workflows to figure out the default values

id_column: "accession"

inputs:
  - name: local_ingest
    metadata: ../ingest/results/metadata.tsv
    sequences: ../ingest/results/sequences.fasta

builds:
  - drc-2025
  - west-africa-2014

build_params:
  drc-2025:
    ancestral:
      inference: joint

    align:
      reference: &Yambuku_Mayinga_Reference outbreak-specific/drc-2025/NC_002549.1.gb  # FIXME: use another reference?

    filter:
      min_length: 10000
      query: outbreak=="Ebov-2025"
      include: outbreak-specific/drc-2025/include.txt

    refine:
      timetree: false
      coalescent: skyline
      date_inference: marginal

    translate:
      reference: *Yambuku_Mayinga_Reference

    traits:
      columns:
        - country
        - division

    export:
      warning: >-
        Work in progress.
      lat_longs: defaults/lat_longs.tsv
      auspice_config: outbreak-specific/drc-2025/auspice_config.json
      description: outbreak-specific/drc-2025/description.md

  west-africa-2014:
    ancestral:
      inference: joint

    align:
      reference: &Makona_Liberia_Reference outbreak-specific/west-africa-2014/ebola_outgroup.gb

    filter:
      min_length: 18000
      exclude_where: is_lab_host=true
      query: (outbreak=="Ebov-2013" | outbreak=="Ebov-2013/r2021")
      subsample_max_sequences: 30
      include: outbreak-specific/west-africa-2014/include.txt
      group_by:
        - division
        - year
        - month

    translate:
      reference: *Makona_Liberia_Reference

    refine:
      timetree: true
      coalescent: skyline
      date_inference: marginal

    traits:
      columns:
        - country
        - division

    export:
      warning: outbreak-specific/west-africa-2014/description.md
      lat_longs: defaults/lat_longs.tsv
      auspice_config: outbreak-specific/west-africa-2014/auspice_config.json
      description: outbreak-specific/west-africa-2014/description.md
      colors: outbreak-specific/west-africa-2014/colors.txt